import type { Product, ProductCategory } from "@/types/product";

export const categoryLabels: Record<ProductCategory, string> = {
  "cafes-grains": "Cafes en grains",
  "cafes-moulus": "Cafes moulus",
  capsules: "Capsules",
  packs: "Packs decouverte",
  accessoires: "Accessoires",
};

export const products: Product[] = [
  {
    id: "prd_ethiopia_yirgacheffe",
    name: "Ethiopie Yirgacheffe",
    slug: "ethiopie-yirgacheffe",
    category: "cafes-grains",
    price: 1390,
    image: "/images/products/coffee-ethiopia.svg",
    shortDescription: "Un cafe floral et lumineux, ideal pour les extractions douces.",
    description:
      "Cultive en altitude dans la region de Yirgacheffe, ce lot revele une tasse delicate, vive et elegante. Il apporte une belle signature premium au catalogue.",
    origin: "Yirgacheffe, Ethiopie",
    intensity: 2,
    weight: "250 g",
    stock: 34,
    isFeatured: true,
    notes: ["jasmin", "bergamote", "miel clair"],
    brewingAdvice: "Parfait en V60, Chemex ou cafetiere filtre avec une mouture moyenne.",
    stripeProductId: 'prod_UbK9IwbmHJMq2S',
    stripePriceId: 'price_1Tc7V3QX3TL48xlZPjjIU0Hs'
  },
  {
    id: "prd_colombia_supremo",
    name: "Colombie Supremo",
    slug: "colombie-supremo",
    category: "cafes-grains",
    price: 1290,
    image: "/images/products/coffee-colombia.svg",
    shortDescription: "Rond, equilibre, avec une finale cacao tres accessible.",
    description:
      "Un cafe colombien premium pense pour plaire largement: tasse ronde, acidite douce, corps confortable et notes gourmandes.",
    origin: "Huila, Colombie",
    intensity: 3,
    weight: "250 g",
    stock: 42,
    isFeatured: true,
    notes: ["cacao", "amande", "orange douce"],
    brewingAdvice: "Excellent en espresso doux, moka italienne ou filtre.",
    stripeProductId: 'prod_UbK999aIGHnEVL',
    stripePriceId: 'price_1Tc7V4QX3TL48xlZdS4Zb6Ak'
  },
  {
    id: "prd_brazil_cerrado",
    name: "Bresil Cerrado",
    slug: "bresil-cerrado",
    category: "cafes-grains",
    price: 1190,
    image: "/images/products/coffee-brazil.svg",
    shortDescription: "Un profil noisette et chocolat au lait pour le quotidien.",
    description:
      "Un cafe chaleureux, stable et gourmand, selectionne pour les amateurs d'espressos confortables et peu acides.",
    origin: "Cerrado Mineiro, Bresil",
    intensity: 3,
    weight: "250 g",
    stock: 56,
    isFeatured: false,
    notes: ["noisette", "chocolat au lait", "sucre brun"],
    brewingAdvice: "Reglage fin conseille pour espresso, egalement tres agreable en cafetiere piston.",
    stripeProductId: 'prod_UbK9N45acEZLDh',
    stripePriceId: 'price_1Tc7V5QX3TL48xlZu0tkqfnk',
  },
  {
    id: "prd_rwanda_bourbon",
    name: "Rwanda Bourbon",
    slug: "rwanda-bourbon",
    category: "cafes-moulus",
    price: 1350,
    image: "/images/products/coffee-rwanda.svg",
    shortDescription: "Cafe moulu elegant, fruite, avec une belle longueur.",
    description:
      "Un Bourbon lave aux notes rouges et epicees, moulu pour une preparation simple sans perdre l'esprit cafe de specialite.",
    origin: "Lac Kivu, Rwanda",
    intensity: 3,
    weight: "250 g",
    stock: 21,
    isFeatured: true,
    notes: ["groseille", "the noir", "epices douces"],
    brewingAdvice: "Mouture adaptee filtre et piston. Utiliser une eau peu mineralisee.",
    stripeProductId: 'prod_UbK9nIuHth1onj',
    stripePriceId: 'price_1Tc7V6QX3TL48xlZYXXQwMSI',
  },
  {
    id: "prd_pack_afrique",
    name: "Pack Decouverte Afrique",
    slug: "pack-decouverte-afrique",
    category: "packs",
    price: 3490,
    image: "/images/products/coffee-pack.svg",
    shortDescription: "Trois origines africaines pour comparer les profils en tasse.",
    description:
      "Un coffret pedagogique et premium pour decouvrir les nuances florales, fruitees et epicees des cafes africains.",
    origin: "Ethiopie, Rwanda, Kenya",
    intensity: 3,
    weight: "3 x 200 g",
    stock: 18,
    isFeatured: true,
    notes: ["agrumes", "fruits rouges", "fleurs blanches"],
    brewingAdvice: "Deguster les trois cafes sur la meme methode pour comparer les aromes.",
    stripeProductId: 'prod_UbK92EAeqM1cB7',
  stripePriceId: 'price_1Tc7V7QX3TL48xlZxoVCHzj6',
  },
  {
    id: "prd_pack_espresso",
    name: "Pack Espresso Intense",
    slug: "pack-espresso-intense",
    category: "packs",
    price: 2990,
    image: "/images/products/coffee-espresso-pack.svg",
    shortDescription: "Deux cafes puissants pour espresso avec une crema genereuse.",
    description:
      "Un duo concu pour les machines espresso domestiques, avec du corps, une amertume maitrisee et une finale chocolat.",
    origin: "Bresil et Colombie",
    intensity: 5,
    weight: "2 x 250 g",
    stock: 24,
    isFeatured: false,
    notes: ["cacao noir", "noix", "caramel"],
    brewingAdvice: "Dose recommandee: 18 g pour 36 g en tasse, extraction autour de 28 secondes.",
    stripeProductId: 'prod_UbK9pkml8a7tbF',
    stripePriceId: 'price_1Tc7V8QX3TL48xlZP9G9t2Zb'
  },
  {
    id: "prd_capsules_maison",
    name: "Capsules Maison",
    slug: "capsules-maison",
    category: "capsules",
    price: 890,
    image: "/images/products/coffee-capsules.svg",
    shortDescription: "Capsules compatibles, profil rond et crema soyeuse.",
    description:
      "Une solution pratique pour proposer un achat rapide sans renoncer a une experience cafe soignee.",
    origin: "Assemblage maison",
    intensity: 4,
    weight: "10 capsules",
    stock: 87,
    isFeatured: true,
    notes: ["praline", "cacao", "pain grille"],
    brewingAdvice: "Prechauffer la tasse et lancer une extraction courte pour conserver le corps.",
    stripeProductId: 'prod_UbK95eRXlul6bo',
    stripePriceId: 'price_1Tc7V9QX3TL48xlZck1MoSCn',
  },
  {
    id: "prd_moulin_manuel",
    name: "Moulin Manuel Premium",
    slug: "moulin-manuel-premium",
    category: "accessoires",
    price: 6490,
    image: "/images/products/coffee-accessory.svg",
    shortDescription: "Moulin compact avec reglage precis pour filtre et espresso.",
    description:
      "Un accessoire rassurant pour augmenter le panier moyen et montrer une boutique e-commerce complete.",
    origin: "Acier inoxydable",
    intensity: 1,
    weight: "620 g",
    stock: 12,
    isFeatured: false,
    notes: ["meules acier", "reglage cran par cran", "format voyage"],
    brewingAdvice: "Moudre juste avant preparation pour preserver les aromes.",
    stripeProductId: 'prod_UbK9vC0T1gNWcz',
    stripePriceId: 'price_1Tc7VAQX3TL48xlZk5iriKON',
  },
  {
    id: "prd_cafetiere_piston",
    name: "Cafetiere Piston",
    slug: "cafetiere-piston",
    category: "accessoires",
    price: 3990,
    image: "/images/products/coffee-french-press.svg",
    shortDescription: "Un classique robuste pour une tasse ronde et genereuse.",
    description:
      "Design minimal, verre resistant et filtre metal. Ideal pour accompagner les cafes moulus de la boutique.",
    origin: "Verre borosilicate",
    intensity: 1,
    weight: "600 ml",
    stock: 16,
    isFeatured: false,
    notes: ["verre epais", "filtre inox", "poignee froide"],
    brewingAdvice: "Infuser 4 minutes avec une mouture grossiere puis presser lentement.",
    stripeProductId: 'prod_UbK9deg63S0Z4E',
    stripePriceId: 'price_1Tc7VBQX3TL48xlZpvmMChlD',
  },
  {
    id: "prd_cafe_moulu_doux",
    name: "Cafe Moulu Doux",
    slug: "cafe-moulu-doux",
    category: "cafes-moulus",
    price: 990,
    image: "/images/products/coffee-ground.svg",
    shortDescription: "Un cafe moulu souple et rassurant pour le matin.",
    description:
      "Une reference accessible, ideale pour completer le catalogue avec un produit d'appel credible et qualitatif.",
    origin: "Assemblage Amerique Latine",
    intensity: 2,
    weight: "250 g",
    stock: 63,
    isFeatured: false,
    notes: ["biscuit", "miel", "amande douce"],
    brewingAdvice: "Convient aux cafetieres filtre electriques et piston.",
    stripeProductId: 'prod_UbK9NmCJu55Ynj',
    stripePriceId: 'price_1Tc7VDQX3TL48xlZQ4BGRFLx',
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getFeaturedProducts() {
  return products.filter((product) => product.isFeatured);
}
